"""empty message

Revision ID: 42d33aaa0541
Revises: e073c44fb9bf
Create Date: 2018-08-15 02:27:08.947596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d33aaa0541'
down_revision = 'e073c44fb9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user', sa.Column('code', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'state')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'code')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
