"""empty message

Revision ID: e073c44fb9bf
Revises: a877d5fe81c0
Create Date: 2018-08-14 09:03:57.493637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e073c44fb9bf'
down_revision = 'a877d5fe81c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['image'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'image')
    # ### end Alembic commands ###
